name: CI API Clients

on:
  push:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vérification API
        run: |
          echo "CI API clients"
          cat clients.txt
name: CI API Clients

on:
  push:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vérification API
        run: |
          echo "CI API clients"
          cat clients.txt

